"""Chunk-wise forward/backward over a tree: one trunk and many branches off it.

A branch continues the trunk from a position `start` with its own tokens: its
context is trunk[:start], and the trunk's tokens from `start` on are not in it.
Many continuations of one long context (every assistant turn of an agent trace,
regenerated by the student) then cost the context once, not once per branch:

  naive   sum_b (start_b + len_b) tokens through the model, forward and backward
  tree    len(trunk) + sum_b len_b

and the gradient is still exact: every branch's loss reaches the parameters
through the trunk's K/V and states, not only through its own tokens.

This is SeCO (palingenesis.seco) with branches hung on the trunk's chunk
boundaries. The trunk is cut at every branch start (and every `chunk_size`
tokens); a branch starting at a boundary reads the cache the trunk chunk there
starts from.

  Stage 1  no grad: run the trunk chunks, keep each chunk's starting state
           (bounded-state layers) and the trunk's K/V (full attention).
  Stage 2  for j = k..0: build grad-carrying leaves of boundary j's state; run
           every branch attached at j from them, with its loss, and backpropagate;
           then recompute trunk chunk j from the same leaves and backpropagate the
           relay terms <out, grad> of what it produced. The leaves' gradients add up
           over the branches and the trunk chunk at j before chunk j-1 relays them,
           and the K/V gradients of every later branch and chunk are in the stores
           before chunk j reads them: the reverse order completes every gradient
           before it is used.

The trunk may carry a loss of its own (`trunk_loss_fn`, e.g. distillation on the
recorded turns the trunk contains), computed in its stage-2 recomputation at no
extra forward. Branches write nothing
into the trunk's K/V store (their tokens are nobody's context), so any number of
them can share a boundary.

`tree_hidden_states` is the no-grad counterpart (teachers, evaluation): each
branch runs as soon as the trunk reaches its start, from a copy of the cache.
"""

import bisect
from collections import defaultdict
from collections.abc import Callable
from dataclasses import dataclass

import torch
import torch.nn as nn

from palingenesis import seco
from palingenesis.seco import (
    _ACTIVE,
    _KV,
    _apply_state,
    _attach_stores,
    _backbone,
    _chunk_attention,
    _is_append_only,
    _leafify,
    _new_cache,
    _onto,
    _restore,
    _rng_state,
    _run,
    _seed_kv,
    _set_rng_state,
    _snapshot,
    _state,
    _storable,
    _tensors,
    _uses_chunk_attention,
    differentiable_decode,
)
from palingenesis.seco_attention import KVStore, reset_host_budget


@dataclass
class Branch:
    """`input_ids` [1, L] continuing the trunk from position `start` (context: trunk[:start])."""

    start: int
    input_ids: torch.Tensor


@dataclass
class TreeResult:
    loss: float  # sum of the branch losses (and the trunk's)
    trunk_chunks: int
    branches: int


def _bounds(length: int, starts: list[int], chunk_size: int, min_gap: int = 1) -> list[tuple[int, int]]:
    """The trunk's chunks: cut every `chunk_size` tokens and at branch starts at least
    `min_gap` past the previous cut (a branch between cuts re-reads the gap itself)."""
    cuts = set(range(0, length, chunk_size)) | {length}
    for s in sorted(set(starts)):
        if 0 < s < length and s - max(c for c in cuts if c <= s) >= min_gap:
            cuts.add(s)
    cuts = sorted(cuts)
    return list(zip(cuts[:-1], cuts[1:]))


def _rebase(
    branches: list[Branch], trunk_ids: torch.Tensor, bounds: list[tuple[int, int]]
) -> tuple[list[Branch], list[int]]:
    """Each branch moved to the last trunk boundary at or before its start, carrying the trunk
    tokens in between; and how many leading positions of its output are those (to drop)."""
    cuts = [lo for lo, _ in bounds] + [trunk_ids.shape[1]]
    moved, skip = [], []
    for b in branches:
        cut = cuts[bisect.bisect_right(cuts, b.start) - 1]
        if cut == b.start:
            moved.append(b)
        else:
            moved.append(Branch(cut, torch.cat([trunk_ids[:, cut : b.start], b.input_ids], 1)))
        skip.append(b.start - cut)
    return moved, skip


def _check(trunk_ids: torch.Tensor, branches: list[Branch]) -> None:
    if trunk_ids.dim() != 2 or trunk_ids.shape[0] != 1:
        raise ValueError(f"trunk_ids must be [1, S] (one trunk at a time), got {tuple(trunk_ids.shape)}")
    for b in branches:
        if not 0 <= b.start <= trunk_ids.shape[1]:
            raise ValueError(f"branch start {b.start} outside the trunk (length {trunk_ids.shape[1]})")
        if b.input_ids.dim() != 2 or b.input_ids.shape[0] != 1 or b.input_ids.shape[1] == 0:
            raise ValueError(f"branch input_ids must be [1, L] with L >= 1, got {tuple(b.input_ids.shape)}")


def _cast_dtype(ids: torch.Tensor):
    return torch.get_autocast_dtype("cuda") if ids.is_cuda and torch.is_autocast_enabled("cuda") else None


BRANCH_TOKENS = 16384  # padded tokens per batched branch forward (activation memory)
MIN_GAP = 1024  # trunk tokens between cuts at branch starts (see tree_forward_backward)


def tree_forward_backward(
    model: nn.Module,
    trunk_ids: torch.Tensor,
    branches: list[Branch],
    loss_fn: Callable[[int, torch.Tensor], torch.Tensor],
    *,
    trunk_loss_fn: Callable[[int, int, torch.Tensor], torch.Tensor | None] | None = None,
    chunk_size: int = 4096,
    branch_tokens: int = BRANCH_TOKENS,
    min_gap: int = MIN_GAP,
) -> TreeResult:
    """Accumulate d(sum_b loss_fn(b, hidden_b) + sum_chunks trunk_loss_fn)/d(params) into
    `.grad`; the caller must NOT call `.backward()` afterwards.

    loss_fn(b, hidden): the loss of branch b from its final hidden states [1, L, H]
    (the caller normalizes); it may compute the output head's gradients itself
    (losses._ChunkedHead, fused_rkl), which the scalar's backward then scales.
    trunk_loss_fn(lo, hi, hidden): the loss of trunk positions [lo, hi) from their
    hidden states [1, hi - lo, H], or None when that chunk has none.
    branch_tokens: branches run batched, up to this many (padded) tokens per forward;
    0 runs them one at a time (models whose attention cannot, see _batchable).
    min_gap: the trunk is cut at a branch start only this far past the previous cut; a
    branch in between re-reads the gap in its batched forward (the same computation:
    exact). Cuts make per-pass overhead, re-read tokens are nearly free in a batch.
    """
    _check(trunk_ids, branches)
    bounds = _bounds(trunk_ids.shape[1], [b.start for b in branches], chunk_size, min_gap)
    moved, skip = _rebase(branches, trunk_ids, bounds)
    with _chunk_attention(model), differentiable_decode(model):
        return _tree(
            model, trunk_ids, moved, lambda i, h: loss_fn(i, h[:, skip[i] :]), trunk_loss_fn, bounds, branch_tokens
        )


def _batches(branches: list[Branch], indices: list[int], max_tokens: int) -> list[list[int]]:
    """Groups of branches for batched forwards: by length (little padding), at most
    `max_tokens` padded tokens each (a longer branch runs alone)."""
    order = sorted(indices, key=lambda i: branches[i].input_ids.shape[1])
    groups, group = [], []
    for i in order:
        width = branches[i].input_ids.shape[1]  # the longest so far (sorted)
        if group and width * (len(group) + 1) > max_tokens:
            groups.append(group)
            group = []
        group.append(i)
    if group:
        groups.append(group)
    return groups


def _stacked(states: list[dict]) -> dict:
    """Per-row states of one layer [1, ...] stacked into a batch (flags taken from the first)."""
    first = states[0]
    return {path: (torch.cat([s[path] for s in states]) if torch.is_tensor(v) else v) for path, v in first.items()}


def _padded(branches: list[Branch], group: list[int]) -> tuple[torch.Tensor, torch.Tensor]:
    """Right-padded input ids [B, L] and each row's positions (its start + offset)."""
    width = max(branches[i].input_ids.shape[1] for i in group)
    device = branches[group[0]].input_ids.device
    ids = torch.zeros(len(group), width, dtype=torch.long, device=device)
    for r, i in enumerate(group):
        ids[r, : branches[i].input_ids.shape[1]] = branches[i].input_ids[0]
    starts = torch.tensor([branches[i].start for i in group], device=device)
    return ids, starts[:, None] + torch.arange(width, device=device)


def _batchable(in_store: list[bool], append: list[bool]) -> bool:
    """Branches from different positions can share one forward when every full-attention
    layer reads the trunk from a KV store (per-row prefix lengths); layers that keep K/V
    in the cache itself (non-sdpa attention, hybrid attention layers) cannot."""
    return all(stored or not app for stored, app in zip(in_store, append))


def _tree(model, trunk_ids, branches, loss_fn, trunk_loss_fn, bounds, branch_tokens) -> TreeResult:
    backbone = _backbone(model)
    if getattr(backbone, "gradient_checkpointing", False) and backbone.training:
        raise RuntimeError(
            "the tree forward needs the cache during training, which HF gradient checkpointing "
            "disables. Use palingenesis activation checkpointing instead."
        )
    seq_len = trunk_ids.shape[1]
    k = len(bounds)
    lo_index = {lo: j for j, (lo, _) in enumerate(bounds)}
    boundary = [k if b.start == seq_len else lo_index[b.start] for b in branches]
    cast = _cast_dtype(trunk_ids)
    use_stores = _uses_chunk_attention(backbone)
    stores: dict[int, KVStore] = {}
    reset_host_budget()
    devices = [trunk_ids.device] if trunk_ids.device.type == "cuda" else []

    # ── Stage 1: the trunk, no grad; the state every boundary starts from ────
    cache = _new_cache(backbone, cast)
    append = [_is_append_only(layer) for layer in cache.layers]
    in_store = [app and use_stores and _storable(layer) for layer, app in zip(cache.layers, append)]
    starts: list[list[dict]] = []
    rng_states = []
    with torch.no_grad():
        for lo, hi in bounds:
            starts.append([_state(layer, app, clone=True) for layer, app in zip(cache.layers, append)])
            rng_states.append(_rng_state(devices))
            _attach_stores(cache, in_store, stores, seq_len, lo, write=True, offload=False)
            _run(backbone, trunk_ids[:, lo:hi], cache)
        starts.append([_state(layer, app, clone=True) for layer, app in zip(cache.layers, append)])  # boundary k
    kv = [
        tuple(getattr(layer, a).detach().requires_grad_(True) for a in _KV)
        if app and not stored and seq_len and getattr(layer, "is_initialized", False)
        else None
        for layer, app, stored in zip(cache.layers, append, in_store)
    ]
    del cache
    for store in stores.values():
        store.start_gradients()

    # Grad-carrying leaves of every boundary's state: the branches and the trunk chunk
    # starting there all read (clones of) them, and their gradients meet in them.
    bound_lo = [lo for lo, _ in bounds] + [seq_len]
    leaves = [
        [(_leafify(_onto(s, trunk_ids.device)) if bound_lo[j] > 0 else {}) for s in starts[j]] for j in range(k + 1)
    ]
    del starts

    def clones(state: dict) -> dict:
        # Clones of the leaves (the gradient still reaches them): a one-token forward updates the
        # conv state in place (transformers' decode path), which a leaf does not allow, and the
        # same leaves serve every branch at this boundary and the trunk chunk.
        return {path: (v.clone() if torch.is_tensor(v) and v.requires_grad else v) for path, v in state.items()}

    def fresh_cache(lo, states: list[dict]):
        cache = _new_cache(backbone, cast)
        _attach_stores(cache, in_store, stores, seq_len, lo, write=False, offload=False)
        for idx, (layer, app) in enumerate(zip(cache.layers, append)):
            _apply_state(layer, states[idx])
            if app and isinstance(lo, int) and lo > 0 and not in_store[idx] and kv[idx] is not None:
                _seed_kv(layer, [t[..., :lo, :] for t in kv[idx]])
        return cache

    total = 0.0

    # ── Stage 2a: every branch (they depend on nothing but the trunk) ───────
    batched = branch_tokens > 0 and _batchable(in_store, append)
    first = [i for i, b in enumerate(branches) if b.start > 0] if batched else []
    groups = _batches(branches, first, branch_tokens) if batched else []
    groups += [[i] for i in range(len(branches)) if not batched or branches[i].start == 0]
    for group in groups:
        if len(group) == 1:
            i = group[0]
            cache = fresh_cache(branches[i].start, [clones(s) for s in leaves[boundary[i]]])
            ids, positions = branches[i].input_ids, None
        else:
            cache = fresh_cache(
                [branches[i].start for i in group],
                [_stacked([clones(leaves[boundary[i]][idx]) for i in group]) for idx in range(len(append))],
            )
            ids, positions = _padded(branches, group)
        before = [_snapshot(layer) for layer in cache.layers]
        hidden = _run(backbone, ids, cache, positions)
        for layer, state in zip(cache.layers, before):  # activation checkpointing re-runs forwards
            _restore(layer, state)
        loss = sum(loss_fn(i, hidden[r : r + 1, : branches[i].input_ids.shape[1]]) for r, i in enumerate(group))
        if loss.requires_grad:
            loss.backward()
        total += float(loss.detach())
        del cache, hidden, loss, before

    # ── Stage 2b: the trunk, reverse sweep with gradient relay ──────────────
    for j in range(k - 1, -1, -1):
        lo, hi = bounds[j]
        cache = fresh_cache(lo, [clones(s) for s in leaves[j]])
        before = [_snapshot(layer) for layer in cache.layers]
        with torch.random.fork_rng(devices=devices):
            _set_rng_state(rng_states[j], devices)
            hidden = _run(backbone, trunk_ids[:, lo:hi], cache)
        # The relay: d<out, grad>/dθ for every output a later branch or chunk read, passed to
        # autograd as (root, incoming gradient) pairs (no scalar to build).
        roots, grads = [], []
        for idx, (layer, app) in enumerate(zip(cache.layers, append)):
            pairs = []
            if in_store[idx]:
                store = stores[idx]
                chunk_k, chunk_v = layer._chunk_kv
                pairs += [(chunk_k, store.grad_k[..., lo:hi, :]), (chunk_v, store.grad_v[..., lo:hi, :])]
            elif app and kv[idx] is not None:
                pairs += [
                    (getattr(layer, a)[..., lo:, :], None if leaf.grad is None else leaf.grad[..., lo:hi, :])
                    for a, leaf in zip(_KV, kv[idx])
                ]
            after = _state(layer, app, clone=False)
            pairs += [(after[path], leaf.grad) for path, leaf in _tensors(leaves[j + 1][idx])]
            for out, grad in pairs:
                if grad is not None and out.requires_grad:
                    roots.append(out)
                    grads.append(grad.to(out.dtype))
        for layer, state in zip(cache.layers, before):
            _restore(layer, state)
        chunk_loss = trunk_loss_fn(lo, hi, hidden) if trunk_loss_fn is not None else None
        if chunk_loss is not None:
            total += float(chunk_loss.detach())
            if chunk_loss.requires_grad:
                roots.append(chunk_loss)
                grads.append(torch.ones_like(chunk_loss))
        if roots:
            torch.autograd.backward(roots, grads)
        del cache, hidden, before, chunk_loss, roots, grads
        leaves[j + 1] = None  # its gradients are relayed: free it
    _ACTIVE.clear()
    return TreeResult(loss=total, trunk_chunks=k, branches=len(branches))


@torch.no_grad()
def tree_hidden_states(
    model: nn.Module,
    trunk_ids: torch.Tensor,
    branches: list[Branch],
    *,
    trunk_positions: list[int] | None = None,
    chunk_size: int = 4096,
    branch_tokens: int = BRANCH_TOKENS,
    min_gap: int = MIN_GAP,
) -> tuple[list[torch.Tensor], torch.Tensor | None]:
    """Final hidden states [1, L, H] of every branch (no grad), the trunk run once; and the
    trunk's own at `trunk_positions` [P, H] (sorted ascending), collected on the way."""
    _check(trunk_ids, branches)
    bounds = _bounds(trunk_ids.shape[1], [b.start for b in branches], chunk_size, min_gap)
    moved, skip = _rebase(branches, trunk_ids, bounds)
    hidden, trunk_hidden = _tree_hidden(model, trunk_ids, moved, trunk_positions, bounds, branch_tokens)
    return [h[:, s:] for h, s in zip(hidden, skip)], trunk_hidden


def _tree_hidden(model, trunk_ids, branches, trunk_positions, bounds, branch_tokens):
    with _chunk_attention(model):
        backbone = _backbone(model)
        seq_len = trunk_ids.shape[1]
        at: dict[int, list[int]] = defaultdict(list)
        for i, b in enumerate(branches):
            at[b.start].append(i)
        cast = _cast_dtype(trunk_ids)
        use_stores = _uses_chunk_attention(backbone)
        stores: dict[int, KVStore] = {}
        reset_host_budget()
        cache = _new_cache(backbone, cast)
        append = [_is_append_only(layer) for layer in cache.layers]
        in_store = [app and use_stores and _storable(layer) for layer, app in zip(cache.layers, append)]
        batched = branch_tokens > 0 and _batchable(in_store, append)
        out: list[torch.Tensor | None] = [None] * len(branches)
        wanted = sorted(trunk_positions or [])
        collected: list[torch.Tensor] = []
        snapshots: dict[int, list[dict]] = {}

        def branch_cache(pos, states: list[dict], src=None):
            new = _new_cache(backbone, cast)
            _attach_stores(new, in_store, stores, seq_len, pos, write=False, offload=False)
            for idx, layer in enumerate(new.layers):
                _apply_state(layer, states[idx])
                if (
                    src is not None
                    and append[idx]
                    and not in_store[idx]
                    and pos > 0
                    and getattr(src.layers[idx], "is_initialized", False)
                ):
                    _seed_kv(layer, [getattr(src.layers[idx], a)[..., :pos, :] for a in _KV])
            return new

        def at_position(pos: int) -> None:
            if not at.get(pos):
                return
            if batched and pos > 0:  # snapshot now, run once the store holds the whole trunk
                snapshots[pos] = [_state(layer, app, clone=True) for layer, app in zip(cache.layers, append)]
                return
            for i in at[pos]:
                states = [_state(layer, app, clone=True) for layer, app in zip(cache.layers, append)]
                out[i] = _run(backbone, branches[i].input_ids, branch_cache(pos, states, cache))

        try:
            for lo, hi in bounds:
                at_position(lo)
                _attach_stores(cache, in_store, stores, seq_len, lo, write=True, offload=False)
                hidden = _run(backbone, trunk_ids[:, lo:hi], cache)
                a, b = bisect.bisect_left(wanted, lo), bisect.bisect_left(wanted, hi)
                if b > a:
                    collected.append(hidden[0, torch.tensor(wanted[a:b], device=hidden.device) - lo])
            at_position(seq_len)
            if snapshots:
                pending = [i for pos in snapshots for i in at[pos]]
                for group in _batches(branches, pending, branch_tokens):
                    states = [
                        _stacked([snapshots[branches[i].start][idx] for i in group]) for idx in range(len(append))
                    ]
                    ids, positions = _padded(branches, group)
                    hidden = _run(backbone, ids, branch_cache([branches[i].start for i in group], states), positions)
                    for r, i in enumerate(group):
                        out[i] = hidden[r : r + 1, : branches[i].input_ids.shape[1]]
        finally:
            _ACTIVE.clear()
        return out, (torch.cat(collected) if collected else None)


__all__ = ["Branch", "TreeResult", "seco", "tree_forward_backward", "tree_hidden_states"]
